/*
 * QEMU OpenTitan OTP Darjeeling partitions
 *
 * Slots that are not explictly filled evaluate to LC_TK_INVALID.
 *
 * Copyright (c) 2024 Rivos, Inc.
 *
 * Author(s):
 *  Emmanuel Blot <eblot@rivosinc.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

/* clang-format off */

/* this prevents linters from checking this file without its parent file */
#ifdef HW_OPENTITAN_OT_OTP_H

static const OtOTPPartDesc OtOTPPartDescs[] = {
    [OTP_PART_VENDOR_TEST] = {
        .size = OTP_PART_VENDOR_TEST_SIZE,
        .offset = OTP_PART_VENDOR_TEST_OFFSET,
        .digest_offset = A_VENDOR_TEST_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = false,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_CREATOR_SW_CFG] = {
        .size = OTP_PART_CREATOR_SW_CFG_SIZE,
        .offset = OTP_PART_CREATOR_SW_CFG_OFFSET,
        .digest_offset = A_CREATOR_SW_CFG_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_OWNER_SW_CFG] = {
        .size = OTP_PART_OWNER_SW_CFG_SIZE,
        .offset = OTP_PART_OWNER_SW_CFG_OFFSET,
        .digest_offset = A_OWNER_SW_CFG_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_OWNERSHIP_SLOT_STATE] = {
        .size = OTP_PART_OWNERSHIP_SLOT_STATE_SIZE,
        .offset = OTP_PART_OWNERSHIP_SLOT_STATE_OFFSET,
        .digest_offset = UINT16_MAX,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = false,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_ROT_CREATOR_AUTH] = {
        .size = OTP_PART_ROT_CREATOR_AUTH_SIZE,
        .offset = OTP_PART_ROT_CREATOR_AUTH_OFFSET,
        .digest_offset = A_ROT_CREATOR_AUTH_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_ROT_OWNER_AUTH_SLOT0] = {
        .size = OTP_PART_ROT_OWNER_AUTH_SLOT0_SIZE,
        .offset = OTP_PART_ROT_OWNER_AUTH_SLOT0_OFFSET,
        .digest_offset = A_ROT_OWNER_AUTH_SLOT0_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_ROT_OWNER_AUTH_SLOT1] = {
        .size = OTP_PART_ROT_OWNER_AUTH_SLOT1_SIZE,
        .offset = OTP_PART_ROT_OWNER_AUTH_SLOT1_OFFSET,
        .digest_offset = A_ROT_OWNER_AUTH_SLOT1_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_PLAT_INTEG_AUTH_SLOT0] = {
        .size = OTP_PART_PLAT_INTEG_AUTH_SLOT0_SIZE,
        .offset = OTP_PART_PLAT_INTEG_AUTH_SLOT0_OFFSET,
        .digest_offset = A_PLAT_INTEG_AUTH_SLOT0_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_PLAT_INTEG_AUTH_SLOT1] = {
        .size = OTP_PART_PLAT_INTEG_AUTH_SLOT1_SIZE,
        .offset = OTP_PART_PLAT_INTEG_AUTH_SLOT1_OFFSET,
        .digest_offset = A_PLAT_INTEG_AUTH_SLOT1_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT0] = {
        .size = OTP_PART_PLAT_OWNER_AUTH_SLOT0_SIZE,
        .offset = OTP_PART_PLAT_OWNER_AUTH_SLOT0_OFFSET,
        .digest_offset = A_PLAT_OWNER_AUTH_SLOT0_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT1] = {
        .size = OTP_PART_PLAT_OWNER_AUTH_SLOT1_SIZE,
        .offset = OTP_PART_PLAT_OWNER_AUTH_SLOT1_OFFSET,
        .digest_offset = A_PLAT_OWNER_AUTH_SLOT1_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT2] = {
        .size = OTP_PART_PLAT_OWNER_AUTH_SLOT2_SIZE,
        .offset = OTP_PART_PLAT_OWNER_AUTH_SLOT2_OFFSET,
        .digest_offset = A_PLAT_OWNER_AUTH_SLOT2_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT3] = {
        .size = OTP_PART_PLAT_OWNER_AUTH_SLOT3_SIZE,
        .offset = OTP_PART_PLAT_OWNER_AUTH_SLOT3_OFFSET,
        .digest_offset = A_PLAT_OWNER_AUTH_SLOT3_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_EXT_NVM] = {
        .size = OTP_PART_EXT_NVM_SIZE,
        .offset = OTP_PART_EXT_NVM_OFFSET,
        .digest_offset = UINT16_MAX,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = false,
        .rd_lockable = true,
        .integrity = false,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_ROM_PATCH] = {
        .size = OTP_PART_ROM_PATCH_SIZE,
        .offset = OTP_PART_ROM_PATCH_OFFSET,
        .digest_offset = A_ROM_PATCH_DIGEST,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_HW_CFG0] = {
        .size = OTP_PART_HW_CFG0_SIZE,
        .offset = OTP_PART_HW_CFG0_OFFSET,
        .digest_offset = A_HW_CFG0_DIGEST,
        .hw_digest = true,
        .sw_digest = false,
        .secret = false,
        .buffered = true,
        .wr_lockable = true,
        .rd_lockable = false,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_HW_CFG1] = {
        .size = OTP_PART_HW_CFG1_SIZE,
        .offset = OTP_PART_HW_CFG1_OFFSET,
        .digest_offset = A_HW_CFG1_DIGEST,
        .hw_digest = true,
        .sw_digest = false,
        .secret = false,
        .buffered = true,
        .wr_lockable = true,
        .rd_lockable = false,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
    [OTP_PART_SECRET0] = {
        .size = OTP_PART_SECRET0_SIZE,
        .offset = OTP_PART_SECRET0_OFFSET,
        .digest_offset = A_SECRET0_DIGEST,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = true,
    },
    [OTP_PART_SECRET1] = {
        .size = OTP_PART_SECRET1_SIZE,
        .offset = OTP_PART_SECRET1_OFFSET,
        .digest_offset = A_SECRET1_DIGEST,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = false,
        .wide = true,
    },
    [OTP_PART_SECRET2] = {
        .size = OTP_PART_SECRET2_SIZE,
        .offset = OTP_PART_SECRET2_OFFSET,
        .digest_offset = A_SECRET2_DIGEST,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = true,
        .wide = true,
    },
    [OTP_PART_SECRET3] = {
        .size = OTP_PART_SECRET3_SIZE,
        .offset = OTP_PART_SECRET3_OFFSET,
        .digest_offset = A_SECRET3_DIGEST,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .wr_lockable = true,
        .rd_lockable = true,
        .integrity = true,
        .is_keymgr = true,
        .wide = true,
    },
    [OTP_PART_LIFE_CYCLE] = {
        .size = OTP_PART_LIFE_CYCLE_SIZE,
        .offset = OTP_PART_LIFE_CYCLE_OFFSET,
        .digest_offset = UINT16_MAX,
        .hw_digest = false,
        .sw_digest = false,
        .secret = false,
        .buffered = true,
        .wr_lockable = false,
        .rd_lockable = false,
        .integrity = true,
        .is_keymgr = false,
        .wide = false,
    },
};

#define OTP_PART_COUNT ARRAY_SIZE(OtOTPPartDescs)

#endif /* HW_OPENTITAN_OT_OTP_H */

/* clang-format off */
