/* Generated from otp_ctrl_mmap.hjson with otptool.py */

/* this prevents linters from checking this file without its parent file */
#ifdef OT_OTP_DJ_PARTS

/* clang-format off */
/* NOLINTBEGIN */
static const OtOTPPartDesc OtOTPPartDescs[] = {
    [OTP_PART_VENDOR_TEST] = {
        .size = 64u,
        .offset = 0u,
        .digest_offset = 56u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = false,
    },
    [OTP_PART_CREATOR_SW_CFG] = {
        .size = 336u,
        .offset = 64u,
        .digest_offset = 392u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_OWNER_SW_CFG] = {
        .size = 632u,
        .offset = 400u,
        .digest_offset = 1024u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_OWNERSHIP_SLOT_STATE] = {
        .size = 48u,
        .offset = 1032u,
        .digest_offset = UINT16_MAX,
        .hw_digest = false,
        .sw_digest = false,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_ROT_CREATOR_AUTH] = {
        .size = 1424u,
        .offset = 1080u,
        .digest_offset = 2496u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_ROT_OWNER_AUTH_SLOT0] = {
        .size = 328u,
        .offset = 2504u,
        .digest_offset = 2824u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_ROT_OWNER_AUTH_SLOT1] = {
        .size = 328u,
        .offset = 2832u,
        .digest_offset = 3152u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_PLAT_INTEG_AUTH_SLOT0] = {
        .size = 328u,
        .offset = 3160u,
        .digest_offset = 3480u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_PLAT_INTEG_AUTH_SLOT1] = {
        .size = 328u,
        .offset = 3488u,
        .digest_offset = 3808u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT0] = {
        .size = 328u,
        .offset = 3816u,
        .digest_offset = 4136u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT1] = {
        .size = 328u,
        .offset = 4144u,
        .digest_offset = 4464u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT2] = {
        .size = 328u,
        .offset = 4472u,
        .digest_offset = 4792u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_PLAT_OWNER_AUTH_SLOT3] = {
        .size = 328u,
        .offset = 4800u,
        .digest_offset = 5120u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_EXT_NVM] = {
        .size = 1024u,
        .offset = 5128u,
        .digest_offset = UINT16_MAX,
        .hw_digest = false,
        .sw_digest = false,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = false,
    },
    [OTP_PART_ROM_PATCH] = {
        .size = 9768u,
        .offset = 6152u,
        .digest_offset = 15912u,
        .hw_digest = false,
        .sw_digest = true,
        .secret = false,
        .buffered = false,
        .write_lock = false,
        .read_lock_csr = true,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_HW_CFG0] = {
        .size = 72u,
        .offset = 15920u,
        .digest_offset = 15984u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = false,
        .buffered = true,
        .write_lock = false,
        .read_lock = false,
        .integrity = true,
    },
    [OTP_PART_HW_CFG1] = {
        .size = 16u,
        .offset = 15992u,
        .digest_offset = 16000u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = false,
        .buffered = true,
        .write_lock = false,
        .read_lock = false,
        .integrity = true,
    },
    [OTP_PART_SECRET0] = {
        .size = 40u,
        .offset = 16008u,
        .digest_offset = 16040u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .write_lock = false,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_SECRET1] = {
        .size = 88u,
        .offset = 16048u,
        .digest_offset = 16128u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .write_lock = false,
        .read_lock = true,
        .integrity = true,
    },
    [OTP_PART_SECRET2] = {
        .size = 120u,
        .offset = 16136u,
        .digest_offset = 16248u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .write_lock = false,
        .read_lock = true,
        .integrity = true,
        .iskeymgr_creator = true,
    },
    [OTP_PART_SECRET3] = {
        .size = 40u,
        .offset = 16256u,
        .digest_offset = 16288u,
        .hw_digest = true,
        .sw_digest = false,
        .secret = true,
        .buffered = true,
        .write_lock = false,
        .read_lock = true,
        .integrity = true,
        .iskeymgr_owner = true,
    },
    [OTP_PART_LIFE_CYCLE] = {
        .size = 88u,
        .offset = 16296u,
        .digest_offset = UINT16_MAX,
        .hw_digest = false,
        .sw_digest = false,
        .secret = false,
        .buffered = true,
        .write_lock = false,
        .read_lock = false,
        .integrity = true,
    },
};

#define OTP_PART_COUNT ARRAY_SIZE(OtOTPPartDescs)

/* NOLINTEND */
/* clang-format on */

#endif /* OT_OTP_DJ_PARTS */
